name: 05 - 1 - Event and Activity types

on:
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running when PR is open or synchronize and base branch is main"
