name: 09 - Function

on:
    push:
    workflow_dispatch:

jobs:
    echo-functions:
        runs-on: ubuntu-latest
        steps:
            - name: Print the PR title
              run: echo "${{ github.event_name.title  }}"
            - name: Print the PR lables
              run: echo "${{ toJson(github.event_name.lables)}}"
            - name: Bug step
              if: ${{!cancelled()}} && ${{contains(github.event_name.title, 'fix')}}
              run: echo "i am a bug fix"
            - name: Sleep for 20sec
              run: sleep 20
            - name: Failing Step
              run: exit 1
            - name: I will be skipped
              if: ${{ success()}}
              run: echo "i will print if previous step is success"
            - name: I will be executed
              if: ${{ failure() }}
              run: echo "i will print if previous step is failed"
            - name: I will be executed
              if: ${{ !cancelled() }}
              run: echo "i will always print, except when the previous step is cancelled"
            - name: I will be executed if cancelled
              if: ${{ cancelled() }}
              run: echo "i will print if any previous step iss cancelled"
              