name: Notify Stale Branches

on:
  schedule:
    - cron: '0 9 * * *' # Runs every day at 9 AM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  notify-stale-branches:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_TOKEN: ${{ vars.GIT_CLI_TOKEN }}
      EMAIL_SENDER: "your-email@example.com"
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq mailutils

      - name: Find Stale Branches and Notify Owners
        run: |
          DAYS_OLD=30
          GRACE_PERIOD=7
          NOTIFIED_BRANCHES=()

          for BRANCH in $(gh repo list-branches --json name,lastCommit --jq '.[] | select(.name | IN("main","develop") | not) | select(.lastCommit.committedDate < (now - (60*60*24*'"$DAYS_OLD"'))) | .name'); do
            PR_COUNT=$(gh pr list --state open --head "$BRANCH" --json id --jq 'length')

            if [[ $PR_COUNT -eq 0 ]]; then
              OWNER_EMAIL=$(gh api repos/${{ github.repository }}/branches/$BRANCH | jq -r '.commit.author.email')
              NOTIFIED_BRANCHES+=("$BRANCH")

              echo "Notifying owner of branch: $BRANCH ($OWNER_EMAIL)"
              echo "$BRANCH,$OWNER_EMAIL" >> stale_branches.csv
            fi
          done

          if [[ ${#NOTIFIED_BRANCHES[@]} -gt 0 ]]; then
            echo "Stale branches found, sending notifications..."
          else
            echo "No stale branches found, skipping notifications."
          fi