name: 12 - outputs

on:
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                description: select the choice of status
                options:
                    - success
                    - failure
                default: success

jobs:
    Build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{steps.build.outputs.status}}
        steps:
            - name: Print GITHUB_OUTPUT paths
              run: echo "$GITHUB_OUTPUT"
            - name: Build
              id: build
              run: echo "status=${{inputs.build-status}}" >> $GITHUB_OUTPUT
    Deploy:
        runs-on: ubuntu-latest
        needs: Build
        if: ${{needs.Build.outputs.build-status == 'success'}}
        steps:
            - name: Deploy
              run: echo "Deployment is completed"