name: 13 - Caching Python CI files

on:
    workflow_dispatch:

jobs:
    build-addition:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./python
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - name: Setup the Python env
              uses: actions/setup-python@v3
              with:
                python-version: '3.9'
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest
            - name: List files in python directory
              run: tree
            - name: Run Unit test
              run: |
                python -m pytest addition.py
            - name: Deploy to Non prod
              run: echo "Deploy to Non prod success"
    build-flask:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - name: Setup the Python env
              uses: actions/setup-python@v3
              with:
                python-version: '3.9'
            - name: Create and activate virtual environment
              run: |
                python -m venv venv
                source venv/bin/activate
            - name: Ensure user `pip` installations are in `PATH`
              run: |
                echo "$HOME/.local/bin" >> $GITHUB_PATH
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest
            - name: Install Flask Dependencies
              run: |
                pip install --user -r requirements.txt
            - name: Build Flask app
              run: |
                python app.py
            - name: Deploy to Non prod
              run: echo "Deploy to Non prod success"