name: 10 - Python - CI - D1 file

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: python/
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - name: Setup the Python env
              uses: actions/setup-python@v3
              with:
                python-version: '3.9'
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest
                pip install -r requirements.txt
            - name: Run Unit test
              run: |
                python -m pytest addition.py
            - name: Deploy to Non prod
              run: echo "Deploy to Non prod success"