name: 13 - Caching Python CI files

on:
    workflow_dispatch:

jobs:
    build-addition:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./python
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - name: Setup the Python env
              uses: actions/setup-python@v3
              with:
                python-version: '3.9'
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest
            - name: List files in python directory
              run: tree
            - name: Run Unit test
              run: |
                python -m pytest addition.py
            - name: Deploy to Non prod
              run: echo "Deploy to Non prod success"
    build-flask:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - name: Setup the Python env
              uses: actions/setup-python@v3
              with:
                python-version: '3.10'
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install flake8 pytest
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Lint with flake8
              run: |
                # stop the build if there are Python syntax errors or undefined names
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics