name: Main CI Pipeline

on:
    push:
        branches:
          - main
    workflow_dispatch:
        inputs:
            app:
              description:  "The Application choice A, B or C"
              required: true
              default: "A"
              
jobs:
    trigger-reusable:     
        uses: ./.github/workflow/18-ci-reusable.yml
        with: 
            app: ${{ inputs.app }}


